### ISSUE TITLE
Guidelines for installing LCARSDE in a dockerized desktop environment

### ISSUE THREAD

**Issue by capsulecorplab** [lcarsde/lcarsde#3]
First of all, thank you for putting together this awesome project!

I've been building a dockerized desktop environment (using an Ansible template for an Ubuntu Jammy Kasm image) for a Star Trek fan group https://github.com/startrekthefleet/fleet-workspace-image and am attempting to install/configure LCARSDE https://github.com/startrekthefleet/fleet-workspace-image/tree/install-lcarsde. I've downloaded and installed the LCARSDE Debian packages without build errors https://github.com/startrekthefleet/fleet-workspace-image/actions/runs/5452842496, but am kind of stuck/unsure as to how to actually enable it in the image https://github.com/startrekthefleet/fleet-workspace-image/blob/install-lcarsde/playbook.yaml#L255. Any guidelines/suggests would be much appreciated.

Keep up the good work!

**Comment by atennert** [comment]
Thank you for your interest in the project and the work you put in yourself. If I understand you correctly you need to get lcarsde running.

It all starts with the window manager. You need some DM like LightDM. If everything is installed without issues, like you said, then there should be an option for lcarswm in the login screen window manager selection. Select that and then start.

If you want to configure the window manager and the status bar system wide, then you can do so with the configuration files in /etc/lcarsde/

Thank you and keep up the good work as well!

**Comment by capsulecorplab** [comment]
Thanks @atennert!

LightDM should be installed as per https://github.com/startrekthefleet/fleet-workspace-image/blob/install-lcarsde/playbook.yaml#L273. Unfortunately, there's no actual login screen for Kasm (that I know of), so I might have to just have to configure the windows manager and status bar globally. Is there an example configuration file I could use as a starting point for how to do so?

**Comment by atennert** [comment]
Sounds like LightDM is maybe configured to load a default window manager. I'm sure there's a way to configure LightDM to use a certain window manager per default. It needs to use lcarswm as available in `/usr/share/xsessions/lcarswm.desktop`. The more manual way would be to run `startx /usr/bin/startlcarswm`.

**Comment by atennert** [comment]
closed due to inactivity
